!***************************************************************************************
Subroutine INPUT(NAME,TITLE,UNITS,NDX,XSTART,IDX,DXC,NGRID,NDT,DT,NWR,ICOMP,&
	NCOMP,TCOMP,ELV,EDP,REFELV,K,EPS,LAMM,TEMPC,IWAVE,HIN,T,DTWAV,IANG,ZIN,DTANG,DMEAS,&
	IRAND,ISEED,RPERC,IELEV,TELEV,DTELV,IWIND,W,ZWIND,DTWND,TPIN,XLAND,DLAND,XLBDUNE,&
	DLBDUNE,XLCDUNE,DLCDUNE,XSCDUNE,DSCDUNE,XBERMS,DBERMS,XBERME,DBERME,XFORS,DFORS,&
	DFS,D50,BMAX,BAV,IBFILL,XBFS,XBFE,NFILL,XF,EFILL,ISWALL,XSWALL,ISWFAIL,PEFAIL,WEFAIL,&
	HFAIL,IHBOT,SCF,SREMGRID)
	use ArrSize, ONLY: NDXMMax
	use Memoryq_u, ONLY: CHECKONLY,ERROCC
	Use IOHandles, ONLY: fhiCFG
	Use MemoryMain, ONLY: NDXV,WRI,DXV,NrNDXV,NrWRI,NrDXV
	Implicit NONE

	Integer,intent(inout)::IHBOT
	Real(8),intent(inout):: SCF
	Character(Len=*),intent(in):: NAME

	Integer,intent(inout):: UNITS,NDX,IDX,NGRID,NDT,NWR,ICOMP,&
		NCOMP,TCOMP(10),IWAVE,IANG,IRAND,ISEED,IELEV,IWIND,&
		TPIN,IBFILL,NFILL,ISWALL,ISWFAIL
	Real(8),intent(inout):: XSTART,DXC,DT,ELV(3),EDP(3),K,LAMM,TEMPC,&
		HIN,T,DTWAV,ZIN,DTANG,DMEAS,RPERC,TELEV,DTELV,W,ZWIND,DTWND,XLAND,DLAND,&
		XLBDUNE,DLBDUNE,XLCDUNE,DLCDUNE,XSCDUNE,DSCDUNE,XBERMS,DBERMS,XBERME,DBERME,&
		XFORS,DFORS,DFS,D50,BMAX,BAV,XBFS,XBFE,XF(10),EFILL(10),XSWALL,PEFAIL,&
		WEFAIL,HFAIL,REFELV,EPS
	
	LOGICAL,intent(inout):: SREMGRID
	Character,intent(inout):: TITLE*70

	Integer:: I,NSUM,TEMPSREMGRID,WVTYPEDummy,NERR
	Character:: LABEL*4
	!TEMPSREMGRID was made an Integer as it is a flag
	NERR=0
	IHBOT=0
	SCF=0.D0
	!******************* MODEL SETUP *******************
	!*
	!* RUN TITLE
10	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.1 ') GOTO 10
	READ(fhiCFG,505) TITLE
	IF (len_trim(TITLE)==0) TITLE=NAME
	!*
	!* OPEN LOG FILE
	!*
	!* INPUT UNITS (SI=1, AMERICAN CUST.=2)
	20    CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.2 ') GOTO 20
	READ(fhiCFG,*) UNITS
	IF(UNITS/=1.AND.UNITS/=2) THEN
		Call WriUFLOG('ERROR AT A.2: "UNITS" MUST EQUAL 1 OR 2')
		NERR=NERR+1
	End If
	!*
	!* NUMBER OF CELLS AND POSITION OF LANDWARD BOUNDARY
30	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.3 ') GOTO 30
	READ(fhiCFG,*)
	READ(fhiCFG,*) NDX,XSTART
	IF(NDX>NDXMMax) THEN
		Call WriFILOG('"ERROR AT A.3: NDX CANNOT BE GREATER THAN "I0"."',NDXMMax)
		NERR=NERR+1
	End If
	!*
	!* GRID TYPE (CONSTANT=0, VARIABLE=1)
40	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.4 ') GOTO 40
	READ(fhiCFG,*) IDX
	IF(IDX/=0.AND.IDX/=1) THEN
		Call WriUFLOG('ERROR AT A.4: "IDX" MUST EQUAL 0 OR 1')
		NERR=NERR+1
	End If
	IF(IDX==0) THEN
		!*
		!* CONSTANT GRID CELL WIDTH
50		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='A.6 ') GOTO 50
		READ(fhiCFG,*) DXC
	End If
	IF(IDX==1) THEN
		!*
		!* NUMBER OF DIFFERENT GRID CELL REGIONS
60		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='A.8 ') GOTO 60
		READ(fhiCFG,*) NGRID

		If(NGRID > 0)Then
			Allocate(DXV(NGRID));NrDXV=NGRID
			Allocate(NDXV(NGRID));NrNDXV=NGRID
		End If
		!*
		!* GRID CELL WIDTHS AND NUMBER OF CELLS IN EACH REGION FROM
		!* LANDWARD TO SEAWARD BOUNDARY
70		CONTINUE
		READ(fhiCFG,500) LABEL
		IF (LABEL/='A.9 ') GOTO 70
		READ(fhiCFG,*)
		READ(fhiCFG,*) (DXV(I),NDXV(I),I=1,NGRID)
		NSUM=0
		DO 75 I=1,NGRID
			NSUM=NSUM+NDXV(I)
75		CONTINUE
		IF(NSUM/=NDX) THEN
			Call WriUFLOG('ERROR AT A.9: TOTAL NUMBER OF CELLS MUST EQUAL "NDX"')
			NERR=NERR+1
		End If
	End If
	!*
	!* NUMBER OF TIME STEPS AND TIME STEP IN MINUTES
80	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.10') GOTO 80
	READ(fhiCFG,*) NDT,DT
	!*
	!* NUMBER OF INTERMEDIATE OUTPUTS WANTED
90	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.11') GOTO 90
	READ(fhiCFG,*) NWR
	IF(NWR>0 .OR. NWR==-1) THEN
		IF(NWR>10) THEN
			Call WriUFLOG('ERROR AT A.11: "NWR" MUST BE LESS THAN OR EQUAL TO 10')
			NERR=NERR+1
			GOTO 110
		End If
		!*
		!* TIME STEP(S) OF INTERMEDIATE OUTPUT
100		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='A.12') GOTO 100
		If(NWR > 0)Then
			Allocate(WRI(NWR));NrWRI=NWR
			READ(fhiCFG,*) (WRI(I),I=1,NWR)
			DO 105 I=1,NWR
				IF(WRI(I)<1.OR.WRI(I)>NDT) THEN
					Call WriUFLOG('ERROR AT A.12: "WRI(I)" MUST BE IN THE RANGE: 1 TO "NDT"')
					NERR=NERR+1
				End If
105			CONTINUE 
		Else
			If(NWR == -1)Then
				Allocate(WRI(1));NrWRI=1
				READ(fhiCFG,*)WRI(1)
				IF(WRI(1)<1.OR.WRI(1)>NDT) THEN
					Call WriUFLOG('ERROR AT A.12: "WRI(1)" MUST BE IN THE RANGE: 1 TO "NDT"')
					NERR=NERR+1
				End If
			End If
		End If
	End If
	!*
	!* IS A MEASURED PROFILE AVAILABLE FOR COMPARISON? (NO=0, 1=YES)
110	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.13') GOTO 110
	READ(fhiCFG,*) ICOMP
	IF(ICOMP/=0.AND.ICOMP/=1) THEN
		Call WriUFLOG('ERROR AT A.13: "ICOMP" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 140
	End If
	IF(ICOMP==1) THEN
		!*
		!* NUMBER OF COMPARISON PROFILES
		NCOMP=1
		!*
		!* TIME STEP(S) AT WHICH COMPARISON(S) WILL BE MADE
		TCOMP(1)=NDT
	End If
	!*
	!* THREE PROFILE ELEVATION CONTOURS (MAXIMUM HORIZONTAL RECESSION OF
	!* EACH WILL BE DETERMINED)
140	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.14') GOTO 140
	READ(fhiCFG,*)
	READ(fhiCFG,*) ELV(1),ELV(2),ELV(3)
	!*
	!* THREE PROFILE EROSION DEPTHS AND REFERENCE ELEVATION (DISTANCE FROM
	!* POSITION OF REFERENCE ELEVATION ON INITIAL PROFILE TO POSITION OF 
	!* LANDWARD MOST OCCURRENCE OF EACH EROSION DEPTH WILL BE DETERMINED)
150	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.15') GOTO 150
	READ(fhiCFG,*)
	READ(fhiCFG,*)
	READ(fhiCFG,*)
	READ(fhiCFG,*) EDP(1),EDP(2),EDP(3),REFELV
	!*
	!* TRANSPORT RATE COEFFICIENT (m^4/N)
160	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.16') GOTO 160
	READ(fhiCFG,*) K
	IF(K<0.25E-6.OR.K>2.5001E-6) THEN
		Call WriUFLOG('ERROR AT A.16: "K" MUST BE IN THE RANGE: 0.25E-6 TO 2.5E-6')
		NERR=NERR+1
	End If
	!*
	!* COEFFICIENT FOR SLOPE DEPENDENT TERM (m^2/s)
170	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.17') GOTO 170
	READ(fhiCFG,*) EPS
	IF(EPS<0.0001.OR.EPS>0.005001) THEN
		Call WriUFLOG('ERROR AT A.17: "EPS" MUST BE IN THE RANGE: 0.0001 TO 0.005')
		NERR=NERR+1
	End If
	!*
	!* TRANSPORT RATE DECAY COEFFICIENT MULTIPLIER
180	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.18') GOTO 180
	READ(fhiCFG,*) LAMM
	IF(LAMM<0.1.OR.LAMM>2.0) THEN
		Call WriUFLOG('ERROR AT A.18: "LAMM" MUST BE IN THE RANGE: 0.1 TO 2.0')
		NERR=NERR+1
	End If
	!*
	!* WATER TEMPERATURE IN DEGREES C
190	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='A.19') GOTO 190
	READ(fhiCFG,*) TEMPC
	IF(TEMPC<0.OR.TEMPC>40.) THEN
		Call WriUFLOG('ERROR AT A.19: "TEMPC" MUST BE IN THE RANGE: 0.0 TO 40.0')
		NERR=NERR+1
	End If
	!* THE BELOW OPTION WAS ADDED BY NCK 11/18/95 TO GIVE THE OPTION OF ALLOWING
	!* SAND TO MOVE OFF THE GRID, THUS ELIMINATING AN AVALANCHING AT END OF GRID
	!* ERROR
	!*
	!* ALLOWING SAND TO MOVE OFF THE GRID
	SREMGRID=.TRUE.
191	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='B.1' .AND. LABEL/='A.20') GOTO 191
	If(LABEL=='A.20')Then
		READ(fhiCFG,*) TEMPSREMGRID
		IF(TEMPSREMGRID==0)SREMGRID=.FALSE.
		Goto 200
	Else
		Goto 201
	End If
	!******************** WAVES/WATER ELEVATION/WIND ********************
	!*
	!* WAVE TYPE IS IRREGULAR
	200   CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='B.1 ') GOTO 200
201	READ(fhiCFG,*) WVTYPEDummy
	!*
	!* WAVE HEIGHT AND PERIOD INPUT (CONSTANT=0, VARIABLE=1)
210	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='B.2 ') GOTO 210
	READ(fhiCFG,*) IWAVE
	IF(IWAVE/=0.AND.IWAVE/=1) THEN
		Call WriUFLOG('ERROR AT B.2: "IWAVE" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 240
	End If
	IF(IWAVE==0) THEN
		!*
		!* CONSTANT WAVE HEIGHT AND PERIOD
220		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.4 ') GOTO 220
		READ(fhiCFG,*) HIN,T
	End If
	IF(IWAVE==1) THEN
		!*
		!* TIME STEP OF VARIABLE WAVE HEIGHT AND PERIOD INPUT IN MINUTES
230		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.6 ') GOTO 230
		READ(fhiCFG,*) DTWAV
	End If
	!*
	!* WAVE ANGLE INPUT (CONSTANT=0, VARIABLE=1)
240	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='B.7 ') GOTO 240
	READ(fhiCFG,*) IANG
	IF(IANG/=0.AND.IANG/=1) THEN
		Call WriUFLOG('ERROR AT B.7: "IANG" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 270
	End If
	IF(IANG==0) THEN
		!*
		!* CONSTANT WAVE ANGLE
250		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.9 ') GOTO 250
		READ(fhiCFG,*) ZIN
		IF(ZIN>90..OR.ZIN<-90.)THEN
			Call WriUFLOG('ERROR AT B.9: "ZIN" MUST BE IN THE RANGE: -90 TO 90 DEGREES')
			NERR=NERR+1
		End If
	End If
	IF(IANG==1) THEN
		!*
		!* TIME STEP OF VARIABLE WAVE ANGLE INPUT IN MINUTES
260		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.11') GOTO 260
		READ(fhiCFG,*) DTANG
	End If
	!*
	!* WATER DEPTH OF INPUT WAVES (DEEP WATER=0.0)
270	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='B.12') GOTO 270
	READ(fhiCFG,*) DMEAS
	!*
	!* IS RANDOMIZATION OF INPUT WAVE HEIGHT DESIRED? (NO=0, YES=1)
280	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='B.13') GOTO 280
	READ(fhiCFG,*) IRAND
	IF(IRAND/=0.AND.IRAND/=1) THEN
		Call WriUFLOG('ERROR AT B.13: "IRAND" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 300
	End If
	IF(IRAND==1) THEN
		!*
		!* SEED VALUE FOR RANDOMIZER AND PERCENT OF VARIABILITY
290		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.15') GOTO 290
		READ(fhiCFG,*) ISEED,RPERC
		IF(ISEED<1000.OR.ISEED>9999) THEN
			Call WriUFLOG('ERROR AT B.15: "ISEED" MUST BE A FOUR DIGIT Integer')
			NERR=NERR+1
		End If
		IF(RPERC<0.OR.RPERC>100.) THEN
			Call WriUFLOG('ERROR AT B.15: "RPERC" MUST BE IN THE RANGE: 0 TO 100')
			NERR=NERR+1
		End If
	End If
	!*
	!* TOTAL WATER ELEVATION INPUT (CONSTANT=0, VARIABLE=1)
300	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='B.16') GOTO 300
	READ(fhiCFG,*) IELEV
	IF(IELEV/=0.AND.IELEV/=1) THEN
		Call WriUFLOG('ERROR AT B.16: "IELEV" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 330
	End If
	IF(IELEV==0) THEN
		!*
		!* CONSTANT TOTAL WATER ELEVATION
310		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.18') GOTO 310
		READ(fhiCFG,*) TELEV
	End If
	IF(IELEV==1) THEN
		!*
		!* TIME STEP OF VARIABLE TOTAL WATER ELEVATION INPUT IN MINUTES
320		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.20') GOTO 320
		READ(fhiCFG,*) DTELV
	End If
	!*
	!* WIND SPEED AND ANGLE INPUT (CONSTANT=0, VARIABLE=1)
330	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='B.21') GOTO 330
	READ(fhiCFG,*) IWIND
	IF(IWIND/=0.AND.IWIND/=1) THEN
		Call WriUFLOG('ERROR AT B.21: "IWIND" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 360
	End If
	IF(IWIND==0) THEN
		!*
		!* CONSTANT WIND SPEED AND ANGLE
340		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.23') GOTO 340
		READ(fhiCFG,*) W,ZWIND
	End If
	IF(IWIND==1) THEN
		!*
		!* TIME STEP OF VARIABLE WIND SPEED AND ANGLE INPUT IN MINUTES
350		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='B.25') GOTO 350
		READ(fhiCFG,*) DTWND
	End If
	!******************** BEACH ********************
	!*
	!* TYPE OF INPUT PROFILE (ARBITRARY=1, SCHEMETIZED=2)
360	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='C.1 ') GOTO 360
	READ(fhiCFG,*) TPIN
	IF(TPIN/=1.AND.TPIN/=2) THEN
		Call WriUFLOG('ERROR AT C.1: "TPIN" MUST EQUAL 1 OR 2')
		NERR=NERR+1
		GOTO 380
	End If
	IF(TPIN==2) THEN
		!*
		!* POSITION AND ELEVATION OF LANDWARD BOUNDARY, LANDWARD BASE OF DUNE,
		!* LANDWARD CREST OF DUNE, SEAWARD CREST OF DUNE, START OF BERM,
		!* END OF BERM, AND FORESHORE
370		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='C.3 ') GOTO 370
		READ(fhiCFG,*)
		READ(fhiCFG,*)
		READ(fhiCFG,*)
		READ(fhiCFG,*) XLAND,DLAND,XLBDUNE,DLBDUNE,XLCDUNE,DLCDUNE,XSCDUNE,&
			&             DSCDUNE,XBERMS,DBERMS,XBERME,DBERME,XFORS,DFORS
		IF(XLAND>XSTART) THEN
			Call WriUFLOG('ERROR AT C.3: "XLAND" MUST BE LESS THAN OR'&
			&        //' EQUAL TO "XSTART"')
			NERR=NERR+1
		End If
		IF(DFORS>=0.0) THEN
			Call WriUFLOG('ERROR AT C.3: "DFORS" MUST BE LESS THAN 0')
			NERR=NERR+1
		End If
	End If
	!*
	!* DEPTH CORRDSPONDING TO LANDWARD END OF SURF ZONE
380	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='C.4 ') GOTO 380
	READ(fhiCFG,*) DFS

	IF(UNITS==1) THEN
		IF(DFS<0.14999.OR.DFS>0.5001) THEN
			Call WriUFLOG('ERROR AT C.4: "DFS" MUST BE IN THE RANGE: 0.15 TO 0.5 m')
			NERR=NERR+1
		End If
	End If
	IF(UNITS==2) THEN
		IF(DFS<0.4999.OR.DFS>1.6001) THEN
			Call WriUFLOG('ERROR AT C.4: "DFS" MUST BE IN THE RANGE: 0.5 TO 1.6 ft')
			NERR=NERR+1
		End If
	End If       
	!*
	!* EFFECTIVE GRAIN SIZE DIAMETER IN MILLIMETERS
400	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='C.5 ') GOTO 400
	READ(fhiCFG,*) D50
	IF(D50<0.1.OR.D50>1.0) THEN
		Call WriUFLOG('ERROR AT C.5: "D50" MUST BE IN THE RANGE: 0.1 TO 1.0 mm')
		NERR=NERR+1
	End If
	!*
	!* MAXIMUM PROFILE SLOPE PRIOR TO AVALANCHING IN DEGREES
410	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='C.6 ') GOTO 410
	READ(fhiCFG,*) BMAX
	IF(BMAX<15.0.OR.BMAX>90.0) THEN
		Call WriUFLOG('ERROR AT C.6: "BMAX" MUST BE IN THE RANGE: 15 TO 90 DEGREES')
		NERR=NERR+1
	End If
	BAV=BMAX-10.
	!******************** BEACH FILL ********************
	!*
	!* IS A BEACH FILL PRESENT? (NO=0, 1=YES)
420	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='D.1 ') GOTO 420
	READ(fhiCFG,*) IBFILL
	IF(IBFILL/=0.AND.IBFILL/=1) THEN
		Call WriUFLOG('ERROR AT D.1: "IBFILL" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 460
	End If
	IF(IBFILL==1) THEN
		!*
		!* POSITION OF START AND END OF BEACH FILL RELATIVE TO INITIAL PROFILE
430		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='D.3 ')GOTO 430
		READ(fhiCFG,*)
		READ(fhiCFG,*) XBFS,XBFE
		IF(XBFS<XSTART) THEN
			Call WriUFLOG('ERROR AT D.3: "XBFS" MUST BE GREATER THAN OR'&
				//' EQUAL TO "XSTART"')
			NERR=NERR+1
		End If
		!*
		!* NUMBER OF REPRESENTATIVE POINTS BETWEEN START AND END OF BEACH FILL
440		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='D.4 ')GOTO 440
		READ(fhiCFG,*)
		READ(fhiCFG,*) NFILL
		IF(NFILL<1.OR.NFILL>10) THEN
			Call WriUFLOG('ERROR AT D.4: "NFILL" MUST BE IN THE RANGE: 1 TO 10')
			NERR=NERR+1
			GOTO 460
		End If
		!*
		!* POSITION AND ELEVATION OF REPRESENTATIVE POINTS RELATIVE TO
		!* THE INITIAL PROFILE
450		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='D.5 ') GOTO 450
		READ(fhiCFG,*)
		READ(fhiCFG,*) (XF(I),EFILL(I),I=1,NFILL)
		DO 455 I=1,NFILL
			IF(XF(I)<=XBFS.OR.XF(I)>=XBFE) THEN
				Call WriUFLOG('ERROR AT D.5: "XF(I)" MUST BE BETWEEN "XBFS" AND "XBFE"')
				NERR=NERR+1
			End If
			IF(I>1.AND.XF(I)<=XF(I-1)) THEN
				Call WriUFLOG('ERROR AT D.5: "XF(I)" MUST BE IN ASCENDING ORDER')
				NERR=NERR+1
				GOTO 460
			End If
455		CONTINUE
	End If
	!******************** SEAWALL/REVETMENT *********************
	!*
	!* IS A SEAWALL PRESENT? (NO=0, 1=YES)
460	CONTINUE
	READ(fhiCFG,500) LABEL
	IF(LABEL/='E.1 ') GOTO 460
	READ(fhiCFG,*) ISWALL
	IF(ISWALL/=0.AND.ISWALL/=1) THEN
		Call WriUFLOG('ERROR AT E.1: "ISWALL" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 464
	End If
	ISWFAIL=0;XSWALL=0.D0;PEFAIL=0.D0;WEFAIL=0.D0;HFAIL=0.D0
	IF(ISWALL==1) THEN
		!*
		!* POSITION OF SEAWALL RELATIVE TO INITIAL PROFILE
470		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='E.3 ')GOTO 470
		READ(fhiCFG,*) XSWALL
		!*
		!* IS SEAWALL ALLOWED TO FAIL? (NO=0 ,YES=1)
480		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='E.4 ') GOTO 480
		READ(fhiCFG,*) ISWFAIL
		IF(ISWFAIL/=0.AND.ISWFAIL/=1) THEN
			Call WriUFLOG('ERROR AT E.4: "ISWFAIL" MUST EQUAL 0 OR 1')
			NERR=NERR+1
			GOTO 464
		End If
		IF(ISWFAIL==1) THEN
			!*
			!* PROFILE ELEVATION AT SEAWALL WHICH CAUSES FAILURE, TOTAL WATER
			!* ELEVATION AT SEAWALL WHICH CAUSES FAILURE, AND WAVE HEIGHT AT
			!* SEAWALL WHICH CAUSES FAILURE
490			READ(fhiCFG,500) LABEL
			IF(LABEL/='E.6 ') GOTO 490
			READ(fhiCFG,*)
			READ(fhiCFG,*)
			READ(fhiCFG,*) PEFAIL,WEFAIL,HFAIL
		End If
	End If
500	FORMAT(A4)
505	FORMAT(A70)
	! INPUT CONDITIONS FOR HARD BOTTOMS
	!******************** HARD BOTTOM *********************
	!*
	!* IS HARD BOTTOM PRESENT? (NO=0, 1=YES)
	IHBOT=0
464	CONTINUE
	READ(fhiCFG,500,END=510) LABEL
	IF(LABEL/='F.1 ') GOTO 464
	READ(fhiCFG,*) IHBOT
	IF(IHBOT/=0.AND.IHBOT/=1) THEN
		Call WriUFLOG('ERROR AT F.1: "IHBOT" MUST EQUAL 0 OR 1')
		NERR=NERR+1
		GOTO 1000
	End If

510	CONTINUE
	IF(IHBOT==1) THEN
		!
		! READ COEFFICIENT FOR TRANSPORT GROWTH DOWNDRIFT EXPOSED
		! HARD BOTTOM (SCF MUST BE GREATER THAN ZERO)

484		CONTINUE
		READ(fhiCFG,500) LABEL
		IF(LABEL/='F.2 ') GOTO 484
		READ(fhiCFG,*) SCF
		IF(SCF<=0) THEN
			Call WriUFLOG('ERROR AT F.2: "SCF" MUST BE GREATER THAN 0')
			NERR=NERR+1
			GOTO 1000
		End If

	End If

1000 IF(NERR>0) THEN
		Call WriUFLOG('')
		Call WriFILOG('I0" ERROR(S) DETECTED."',NERR)
		Call WriUFLOG('PLEASE CORRECT YOUR CONFIGURATION FILE')
		ErrOcc=.true.
	End If
	RETURN
End Subroutine INPUT
!***************************************************************************************
Subroutine OPENOLD(UNIT,NAME,EXT)
	Use IOHandles, ONLY: fhoSCR,fhoLOG,feiCFG
	Implicit NONE
	Integer,intent(inout):: UNIT
	Character(Len=*),intent(in):: NAME,EXT
	Integer::IORes
	OPEN(UNIT,FILE=Trim(NAME)//trim(EXT),STATUS='OLD',IOStat=IORes)
	If(IORes/=0) then
		WRITE(fhoSCR,*)
		WRITE(fhoSCR,*)'"'//trim(NAME)//trim(EXT)//'" DOES NOT EXIST IN WORKING DIRECTORY.'
		IF(Trim(EXT)/=Trim(feiCFG)) THEN
			WRITE(fhoLOG,*)
			WRITE(fhoLOG,*)'"'//trim(NAME)//trim(EXT)//'" DOES NOT EXIST IN WORKING DIRECTORY.'
		End If
		STOP
	End if
	return
End Subroutine OPENOLD
!***************************************************************************************
Subroutine CHKORDER(UNIT,X,NDAT)
	Use ArrSize
	Use Memoryq_u, ONLY: CHECKONLY,ERROCC
	Use IOHandles, ONLY: fhiPRI,fhiPRM,fhiHDB
	Implicit NONE
	Integer,intent(inout):: UNIT,NDAT
	Real(8),intent(inout):: X(NDX)
	Character:: MSG*21
	Integer:: I

	DO 10 I=2,NDAT
		IF(X(I)<=X(I-1)) GOTO 20
10	CONTINUE
	RETURN

20	IF(UNIT==fhiPRI) MSG='INITIAL PROFILE DATA '
	IF(UNIT==fhiPRM) MSG='MEASURED PROFILE DATA'
	IF(UNIT==fhiHDB) MSG='HARD BOTTOM DATA'
	Call WriUFLOG('')
	Call WriUFLOG('ERROR: '//trim(MSG)//' NOT IN ASCENDING ORDER.')
	ErrOcc=.TRUE.
End Subroutine CHKORDER
!***************************************************************************************
Subroutine HBELEV(NDX,X,DI,DBOT,FACTL)
! ROUTINE TO READ IN THE HARD BOTTOM ELEVATIONS AND TO GENERATE
! VALUES ON THE COMPUTATIONAL GRID
	Use Memoryq_u, ONLY: CHECKONLY,ERROCC,HBX,HBD,HBNRV
	Use IOHandles, ONLY: fhiHDB
	Implicit NONE
	Integer,intent(in):: NDX
	Real(8),intent(inout):: FACTL	
	Real(8),intent(inout):: X(NDX),DBOT(NDX),DI(NDX)

	Real(8),allocatable:: XT(:),DTI(:)
	Integer::istat,I,J,NRV,IBOT

	allocate(XT(NDX),DTI(NDX))
	!
	! READ HARD BOTTOM ELEVATIONS FROM UNIT 17
	!
	NRV=HBNRV
	READ(fhiHDB,*,IOSTAT=istat) NRV
	If(istat /= 0)Then
		Call WriUFLOG('ERROR: INSUFFICIENT NUMBER OF DATA IN HARD BOTTOM FILE.')
		ErrOcc=.true.
		return
	End If

	DO I=1,NRV
		READ(fhiHDB,*,IOSTAT=istat) HBX(I),HBD(I)
		If(istat /= 0)Then
			Call WriUFLOG('ERROR: INSUFFICIENT NUMBER OF DATA IN HARD BOTTOM FILE.')
			ErrOcc=.true.
			return
		End If
		XT(I)=HBX(I)*FACTL
		DTI(I)=-HBD(I)*FACTL
	End Do
	CALL CHKORDER(fhiHDB,XT,NRV)
	If(ErrOcc)return
	IF(XT(1)>X(1).OR.XT(NRV)<X(NDX)) THEN
		Call WriUFLOG('ERROR: HARD BOTTOM DATA DOES NOT COVER RANGE OF SIMULATION')
		ErrOcc=.TRUE.
		return
	End If

	!
	! INTERPOLATE TO OBTAIN HARD BOTTOM ELEVATIONS ON THE GRID
	!
	DO I=1,NDX
		DO J=1,NRV-1
			IF(X(I)>=XT(J).AND.X(I)<XT(J+1)) Exit
		End Do
		DBOT(I)=DTI(J)+(DTI(J+1)-DTI(J))*(X(I)-XT(J))/(XT(J+1)-XT(J))
	End Do

	!
	! CHECK SO THAT HARD BOTTOM IS NOT ABOVE INITIAL PROFILE
	!
	IBOT=0
	DO I=1,NDX
		IF(DBOT(I)<DI(I))THEN
			DBOT(I)=DI(I)
			IBOT=IBOT+1
		End If
	End Do
	IF(IBOT==1)THEN
		Call WriUFLOG('')
		Call WriUFLOG('HARD BOTTOM DATA ABOVE INITIAL PROFILE. ')
		Call WriFILOG('"NUMBER OF ADJUSTMENTS: "I0',IBOT)
	End If
	DeAllocate(XT,DTI)
	RETURN
End Subroutine HBELEV
!***************************************************************************************
Subroutine CHECKNUM(UNIT,NDT,DT,DTPAR)
	Use Memoryq_u,ONLY: CHECKONLY,ERROCC
	Use IOHandles, ONLY: fhiWAV,fhiWND,fhiANG,fhiELV
	Implicit NONE
	Integer,intent(inout):: UNIT,NDT
	Integer ISTAT,NMIN
	Real(8),intent(inout):: DT,DTPAR
	Character MSG*80
	Real(8)::REQ1,REQ2,DAT1,DAT2
	Integer::I
	
	REQ1=Real(NDT-1)*DT/DTPAR+1.
	NMIN=INT(REQ1)
	REQ2=Real(NMIN)
	IF(REQ1>REQ2) NMIN=NMIN+1

	CALL HEADER(UNIT);If(ErrOcc) Return

	DO I=1,NMIN
		IF(UNIT==fhiWAV.OR.UNIT==fhiWND) THEN
			READ(UNIT,*,IOSTAT=istat) DAT1,DAT2
			if(istat /= 0) Exit
		ELSEIF(UNIT==fhiANG.OR.UNIT==fhiELV) THEN
			READ(UNIT,*,IOSTAT=istat) DAT1
			if(istat /= 0) Exit
		ELSE
			ErrOcc=.TRUE.
			Exit
		End If
	End Do
	
	if(.NOT.ErrOcc.and.istat==0)Then
		REWIND(UNIT)
	Else
		ErrOcc=.TRUE.
		IF(UNIT==fhiWAV)THEN
			MSG='WAVE INPUT FILE.'
		End If
		IF(UNIT==fhiANG)THEN
			MSG='WAVE ANGLE INPUT FILE.'
		End If
		IF(UNIT==fhiELV)THEN
			MSG='WATER ELEVATION INPUT FILE.'
		End If
		IF(UNIT==fhiWND)THEN
			MSG='WIND INPUT FILE.'
		End If
		Call WriUFLOG('')
		Call WriUFLOG('INSUFFICIENT NUMBER OF DATA RECORDS IN '//trim(MSG))
		Call WriFILOG('I0" RECORDS ARE REQUIRED FOR GIVEN CONFIGURATION."',NMIN)
	End If
	Return
End Subroutine CHECKNUM
!***************************************************************************************
Subroutine CheckTemporalInfo(NDT,IANG,IWAVE,IWIND,TWAVL,TWAVH,HINL,TL,HINH,TH,TANGL,&
	TANGH,ZINL,ZINH,TELVL,TELVH,DSURGEL,DSURGEH,TWNDL,TWNDH,WL,ZWINDL,WH,ZWINDH,DTWAV,&
	DTANG,DTELV,DTWND,RunSimCode,NAME)
	!* READ FIRST TWO VALUES FROM VARIABLE DATA FILES FOR INTERPOLATION
	Use Memoryq_u,ONLY: ErrOcc
	Use Memory, ONLY: IELEV,DT
	Use IOHandles, ONLY: fhiWAV,fhiANG,fhiWND,fhiELV,feiWAV,feiANG,feiELV,feiWND
	Implicit NONE
	Integer,intent(inout):: NDT,IANG,IWAVE,IWIND
	Real(8),intent(inout):: TWAVL,TWAVH,HINL,TL,HINH,TH,TANGL,TANGH,ZINL,ZINH,TELVL,TELVH,&
		DSURGEL,DSURGEH,TWNDL,TWNDH,WL,ZWINDL,WH,ZWINDH,DTWAV,DTANG,DTELV,DTWND
	Integer,intent(out)::RunSimCode
	Character(Len=*),intent(in):: NAME

	IF(IWAVE==1) THEN
		TWAVL=DT
		TWAVH=DT+DTWAV
		CALL OPENOLD(fhiWAV,NAME,feiWAV)
		CALL CHECKNUM(fhiWAV,NDT,DT,DTWAV)
		if(ErrOcc)Then
			RunSimCode=8
			return
		End if
		CALL HEADER(fhiWAV)
		If(ErrOcc)Then
			RunSimCode=-8
			return
		End IF
		READ(fhiWAV,*) HINL,TL
		READ(fhiWAV,*) HINH,TH
	End If

	IF(IANG==1) THEN
		TANGL=DT
		TANGH=DT+DTANG
		CALL OPENOLD(fhiANG,NAME,feiANG)
		CALL CHECKNUM(fhiANG,NDT,DT,DTANG)
		if(ErrOcc)Then
			RunSimCode=9
			return
		End if
		CALL HEADER(fhiANG)
		If(ErrOcc)Then
			RunSimCode=9
			return
		End IF
		READ(fhiANG,*) ZINL
		READ(fhiANG,*) ZINH
	End If
	IF(IELEV==1) THEN
		TELVL=DT
		TELVH=DT+DTELV
		CALL OPENOLD(fhiELV,NAME,feiELV)
		CALL CHECKNUM(fhiELV,NDT,DT,DTELV)
		if(ErrOcc)Then
			RunSimCode=10
			return
		End if
		CALL HEADER(fhiELV)
		If(ErrOcc)Then
			RunSimCode=10
			return
		End IF
		READ(fhiELV,*) DSURGEL
		READ(fhiELV,*) DSURGEH
	End If
	IF(IWIND==1) THEN
		TWNDL=DT
		TWNDH=DT+DTWND
		CALL OPENOLD(fhiWND,NAME,feiWND)
		CALL CHECKNUM(fhiWND,NDT,DT,DTWND)
		if(ErrOcc)Then
			RunSimCode=11
			return
		End if
		CALL HEADER(fhiWND)
		If(ErrOcc)Then
			RunSimCode=11
			return
		End IF
		READ(fhiWND,*) WL,ZWINDL
		READ(fhiWND,*) WH,ZWINDH
	End If
	return
End Subroutine CheckTemporalInfo
!***************************************************************************************
Subroutine ReadTemporalInfo(IANG,IWAVE,IWIND,OFFSHORE,FACTH,DTR,TWAVL,TWAVH,&
	HINL,TL,HINH,TH,TANGL,TANGH,ZINL,ZINH,TELVL,TELVH,DSURGEL,DSURGEH,TWNDL,&
	TWNDH,WL,ZWINDL,WH,ZWINDH,TRATIO,T,TIME,ZIN,W,ZWIND,HIN,DTWAV,DTANG,DTELV,DTWND,FACTL)
	Use Memory, ONLY: DSURGE,IELEV,LO,PI
	Use IOHandles, ONLY: fhiWAV,fhiANG,fhiWND,fhiELV
	Implicit NONE
	Integer,intent(inout):: IANG,IWAVE,IWIND
	Logical,intent(inout):: OFFSHORE
	Real(8),intent(inout):: FACTH,DTR,TWAVL,TWAVH,HINL,TL,HINH,TH,TANGL,TANGH,ZINL,&
		ZINH,TELVL,TELVH,DSURGEL,DSURGEH,TWNDL,TWNDH,WL,ZWINDL,WH,ZWINDH,TRATIO,&
		T,TIME,ZIN,W,ZWIND,HIN,DTWAV,DTANG,DTELV,DTWND,FACTL
	Logical:: CycleLoop
	
	IF(IWAVE==1) THEN
		CycleLoop=.true.
		Do While(CycleLoop)
			IF(TIME<=TWAVH) THEN
				TRATIO=(TIME-TWAVL)/DTWAV
				HIN=HINL+(HINH-HINL)*TRATIO
				T=TL+(TH-TL)*TRATIO
				CycleLoop=.false.
			ELSE
				TWAVL=TWAVH
				TWAVH=TWAVL+DTWAV
				HINL=HINH
				TL=TH
				READ(fhiWAV,*) HINH,TH
			End If
		End Do
		HIN=HIN*FACTL*facth
		LO=1.5613*T**2
	End If
	IF(IANG==1) THEN
		CycleLoop=.true.
		Do While(CycleLoop)
			IF(TIME<=TANGH) THEN
				TRATIO=(TIME-TANGL)/DTANG
				ZIN=ZINL+(ZINH-ZINL)*TRATIO
				CycleLoop=.false.
			ELSE
				TANGL=TANGH
				TANGH=TANGL+DTANG
				ZINL=ZINH
				READ(fhiANG,*) ZINH
			End If
		End Do
		IF(ZIN<-90.OR.ZIN>90) THEN
			OFFSHORE=.TRUE.
		ELSE
			OFFSHORE=.FALSE.
		End If
		ZIN=ZIN*DTR
	End If
	IF(IELEV==1) THEN
		CycleLoop=.true.
		Do While(CycleLoop)
			IF(TIME<=TELVH) THEN
				TRATIO=(TIME-TELVL)/DTELV
				DSURGE=DSURGEL+(DSURGEH-DSURGEL)*TRATIO
				CycleLoop=.false.
			ELSE
				TELVL=TELVH
				TELVH=TELVL+DTELV
				DSURGEL=DSURGEH
				READ(fhiELV,*) DSURGEH
			End If
		End Do
		DSURGE=DSURGE*FACTL
	End If
	IF(IWIND==1) THEN
		CycleLoop=.true.
		Do While(CycleLoop)
			IF(TIME<=TWNDH) THEN
				TRATIO=(TIME-TWNDL)/DTWND
				W=WL+(WH-WL)*TRATIO
				ZWIND=ZWINDL+(ZWINDH-ZWINDL)*TRATIO
				CycleLoop=.false.
			ELSE
				TWNDL=TWNDH
				TWNDH=TWNDL+DTWND
				WL=WH
				ZWINDL=ZWINDH
				READ(fhiWND,*) WH,ZWINDH
			End If
		End Do
		W=W*FACTL
		ZWIND=ZWIND*atan(1.d0)/4.5d1 !i.e., pi/180 ~ 0.0175
	End If

	Return
End Subroutine
!***************************************************************************************
Subroutine HEADER(UNIT)
	Use Memoryq_u,ONLY: CHECKONLY,ERROCC
	Use IOHandles, ONLY: fhoSCR,fhiWAV,fhiANG,fhiELV,fhiWND,fhiPRI,fhiPRM,fhiHDB
	Implicit NONE
	Integer,intent(inout):: UNIT
	Character MSG*80,CurLine*80
	Integer:: IORes

	do;read(UNIT,'(A)',IOStat=IORes) CurLine
		CurLine=CurLine//' ' !this ensures its at least 1 chr lone
		if(IORes/=0) Exit
		if(CurLine(1:1)=='E') Exit
	End Do

	select case(UNIT)
		case(fhiWAV);MSG='WAVE INPUT FILE.'
		case(fhiANG);MSG='WAVE ANGLE INPUT FILE.'
		case(fhiELV);MSG='WATER ELEVATION INPUT FILE.'
		case(fhiWND);MSG='WIND INPUT FILE.'
		case(fhiPRI);MSG='INITIAL PROFILE INPUT FILE.'
		case(fhiPRM);MSG='MEASURED PROFILE(S) INPUT FILE.'
		case(fhiHDB);MSG='HARD BOTTOM INPUT FILE.'
	case default
		Call WriUFSCROnly('program logic error in HEADER')
	end select
	if(IORes/=0.or.CurLine(1:1)/='E') then
		Call WriUFSCROnly('PLEASE ADD A HEADER TO '//MSG)
		ErrOcc=.true.
	end if
	return
End Subroutine HEADER
!***************************************************************************************
